# Generated by Django 3.2.5 on 2021-07-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puppies_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('breed', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
