# Generated by Django 3.2.5 on 2021-07-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210724_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppies_list',
            name='breed',
            field=models.TextField(),
        ),
    ]
