# Generated by Django 3.2.5 on 2021-07-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_puppies_list_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppies_list',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
