# Generated by Django 3.2.5 on 2021-07-27 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_puppies_list_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppies_list',
            name='date',
            field=models.DateField(null=datetime.datetime.now),
        ),
    ]
